package nuc.bsd.psy.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQuestion<M extends BaseQuestion<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public void setCATEGORY(java.lang.Integer CATEGORY) {
		set("CATEGORY", CATEGORY);
	}

	public java.lang.Integer getCATEGORY() {
		return get("CATEGORY");
	}

	

	
	public void setSTEM(java.lang.String STEM) {
		set("STEM", STEM);
	}

	public java.lang.String getSTEM() {
		return get("STEM");
	}

	public void setIMAGE(java.lang.String IMAGE) {
		set("IMAGE", IMAGE);
	}

	public java.lang.String getIMAGE() {
		return get("IMAGE");
	}

	public void setXXA(java.lang.String XXA) {
		set("XXA", XXA);
	}

	public java.lang.String getXXA() {
		return get("XXA");
	}

	public void setXXB(java.lang.String XXB) {
		set("XXB", XXB);
	}

	public java.lang.String getXXB() {
		return get("XXB");
	}

	public void setXXC(java.lang.String XXC) {
		set("XXC", XXC);
	}

	public java.lang.String getXXC() {
		return get("XXC");
	}

	public void setXXD(java.lang.String XXD) {
		set("XXD", XXD);
	}

	public java.lang.String getXXD() {
		return get("XXD");
	}

	public void setXXE(java.lang.String XXE) {
		set("XXE", XXE);
	}

	public java.lang.String getXXE() {
		return get("XXE");
	}
	public void setXXF(java.lang.String XXF) {
		set("XXF", XXF);
	}

	public java.lang.String getXXF() {
		return get("XXF");
	}


}
