package nuc.bsd.psy.domain;

import nuc.bsd.psy.base.model.BaseDbTester;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DbTester extends BaseDbTester<DbTester> {
	public static final DbTester dao = new DbTester();
}
