package nuc.bsd.psy.domain;

import nuc.bsd.psy.base.model.BaseQuestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Question extends BaseQuestion<Question> {
	public static final Question dao = new Question();
}
